version: '2'
services:
  nginx-proxy_cs:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy_cs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  mariadb_cs:
    image: mariadb:10.1
    container_name: mariadb_cs
    environment:
      - MYSQL_ROOT_PASSWORD=cryptoquant
      - MYSQL_DATABASE=quant
      - MYSQL_USER=quantservice
      - MYSQL_PASSWORD=cryptoquant
      - VIRTUAL_HOST=mariadb_cs.cryptoquant.org
    ports:
     - "3306:3306"
    volumes:
     - "/data/cryptoquant/mariadb:/var/lib/mysql"
  cubes_cs:
    build: ./cube_server
    container_name: cubes_cs
    environment:
      - VIRTUAL_HOST=cube.cryptoquant.org
      - VIRTUAL_PORT=5000
      - JUPYTER_ENDPOINT=false
      - CONNECTION_STRING=mysql+pymysql://root:cryptoquant@mariadb_cs/quant
    volumes:
      - "./cube_server:/srv"
    links:
      - mariadb_cs
  ipynb_cubes_cs:
    build: ./cube_server
    depends_on: 
      - cubes_cs
    container_name: ipynb_cubes_cs
    environment:
      - VIRTUAL_HOST=ipynbcube.cryptoquant.org
      - VIRTUAL_PORT=80
      - IPYTHONDIR=/srv
      - JUPYTER_ENDPOINT=true
      - CONNECTION_STRING=mysql+pymysql://root:cryptoquant@mariadb_cs/quant
    volumes:
      - "./cube_server:/srv"
    links:
      - mariadb_cs
      - cubes_cs
  